apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: nifi-credentials
type: Opaque
stringData:
  credentials: |
    {
      "url": "https://nifi.example.com:8443/nifi-api",
      "username": "admin",
      "password": "changeme",
      "tlsSkipVerify": true
    }
---
apiVersion: nifi.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  nifiVersion: 2
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: nifi-credentials
      key: credentials
